### ISSUE TITLE
ACF Breaks SB3(CAF), One Lua Error breaks SB3 Multiplayer Compleatly.

### ISSUE THREAD

**Issue by benemii** [SnakeSVx/spacebuild#21]
The Armoured Combat Framework Addon, was working completely fine with SB3 a week ago.
But now when you start up single player it gives you this one Error from CAF.

Filename: CAF_Hooks, Message: Think3 Error: addons/spacebuild 3/lua/caf/addons/server/lifesupport.lua:460: attempt to index field 'ls' (a nil value)

And the Gui is stuck at 0,Playermodels are grey and a mess. No tools at all. Here is a screen shot. 

http://steamcommunity.com/sharedfiles/filedetails/?id=107342001

3 other people have reported this problem already. So it is not only me. But removing ACF from your addons will fix this. Question is. What happened between a week ago and today that would cause ACF to break SB3(CAF) It was working completely fine.

**Comment by generalwrex** [comment]
Closing all old open issues, please reopen or create a new one if these problems still exist! ( Im General Wrex now ;) )
