### ISSUE TITLE
Environmental Controls\Air Hydroponics\Air Hydroponics Tool Does Not Generate Object

### ISSUE THREAD

**Issue by kbernges** [SnakeSVx/spacebuild#30]
Thus rendering impossible CO2-->O2 conversion, resulting in irreversible gradual reduction of atmospheric O2 quantity and gain in CO2 quantity (due to the breathing simulation). Only possible true compensation without causing gradual pressure increase is splitting water and venting O2 into the atmosphere at a controlled rate whilst venting H2 and CO2 into space, which requires an incredibly complicated setup. Without this, it is possible to drain a map completely of all O2 on every world.

**Comment by generalwrex** [comment]
Closing all old open issues, please reopen or create a new one if these problems still exist!
