### ISSUE TITLE
rename SetMaterialFloat to SetFloat

### ISSUE THREAD

**Issue by X-Coder** [SnakeSVx/spacebuild#36]
Some small fix for "lua/effects/warpcore_breach/init.lua", just rename SetMaterialFloat (which was renamed by garry) to SetFloat.

Oh and maybe you can figure out why this effect has a black flickering border like some alphachannel is not working?

**Comment by generalwrex** [comment]
Closing all old open issues, please reopen or create a new one if these problems still exist!
