### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by nexbr** [SnakeSVx/spacebuild#40]
[MkLBR|4|STEAM_0:0:39166068] Lua Error:

[ERROR] lua/includes/util.lua:33: bad argument #1 to 'min' (number expected, got
 nil)
  1. min - [C]:-1
   2. Color - lua/includes/util.lua:33
    3. Beam_Render - ...acebuild3/lua/caf/addons/client/resourcedistribution.lua
:653
     4. unknown - ...spacebuild3/lua/entities/base_sb_environment/cl_init.lua:16

[MkLBR|4|STEAM_0:0:39166068] Lua Error:

[ERROR] lua/includes/util.lua:33: bad argument #1 to 'min' (number expected, got
 nil)
  1. min - [C]:-1
   2. Color - lua/includes/util.lua:33
    3. Beam_Render - ...acebuild3/lua/caf/addons/client/resourcedistribution.lua
:653
     4. unknown - ...spacebuild3/lua/entities/base_sb_environment/cl_init.lua:16

[MkLBR|4|STEAM_0:0:39166068] Lua Error:

[ERROR] lua/includes/util.lua:33: bad argument #1 to 'min' (number expected, got
 nil)
  1. min - [C]:-1
   2. Color - lua/includes/util.lua:33
    3. Beam_Render - ...acebuild3/lua/caf/addons/client/resourcedistribution.lua
:653
     4. unknown - ...spacebuild3/lua/entities/base_sb_environment/cl_init.lua:16

[MkLBR|4|STEAM_0:0:39166068] Lua Error:

[ERROR] lua/includes/util.lua:33: bad argument #1 to 'min' (number expected, got
 nil)
  1. min - [C]:-1
   2. Color - lua/includes/util.lua:33
    3. Beam_Render - ...acebuild3/lua/caf/addons/client/resourcedistribution.lua
:653
     4. unknown - ...spacebuild3/lua/entities/base_sb_environment/cl_init.lua:16

[MkLBR|4|STEAM_0:0:39166068] Lua Error:

[ERROR] lua/includes/util.lua:33: bad argument #1 to 'min' (number expected, got
 nil)
  1. min - [C]:-1
   2. Color - lua/includes/util.lua:33
    3. Beam_Render - ...acebuild3/lua/caf/addons/client/resourcedistribution.lua
:653
     4. unknown - ...spacebuild3/lua/entities/base_sb_environment/cl_init.lua:16

[ERROR] addons/spacebuild3/lua/autorun/client/cl_caf_autostart.lua:207: attempt to call field 'Get' (a nil value)
  1. IsUpToDate - addons/spacebuild3/lua/autorun/client/cl_caf_autostart.lua:207
   2. AddCAFInfoToStatus - addons/spacebuild3/lua/autorun/client/cl_caf_autostart.lua:534
    3. GetStatusPanel - addons/spacebuild3/lua/autorun/client/cl_caf_autostart.lua:605
     4. unknown - addons/spacebuild3/lua/autorun/client/cl_caf_autostart.lua:788
      5. unknown - lua/includes/modules/concommand.lua:69

**Comment by generalwrex** [comment]
Closing all old open issues, please reopen or create a new one if these problems still exist!
