### ISSUE TITLE
CAF Main Menu all grey plus missing tab icons

### ISSUE THREAD

**Issue by lviolal** [SnakeSVx/spacebuild#67]
Well the title here almost tells it all.
When I try to open the main menu of CAF (loaded the latest version here), I just see the tabs but nothing in there, just grey. There are also missing some tab icons.
I'm not into the code here, but if there is a way to deactivate for example life support from launch on, I'd be interested into getting to know how.
Viola

**Comment by generalwrex** [comment]
I'm going to close this issue for now as it seems to be working. Reopen this if it isn't true!
