### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by Nueblah** [SnakeSVx/spacebuild#69]
Two files i need are missing. I saw a red exclamation mark on the svn file and then said SVN Commit. the files are Path	Filename	Extension	Status	Remote status	Text status	Property status	Remote text status	Remote property status	Depth	URL	Lock	Lock comment	Lock Date	Author	Revision	Remote revision	Date	Modification date	Size
tags/2.1.1/README.md	README.md	.md	deleted	???	normal	 	???	???	Unknown depth	tags/2.1.1/README.md						???			65 bytes
tags/v3.1.0/README.md	README.md	.md	deleted	???	normal	 	???	???	Unknown depth	tags/v3.1.0/README.md						???			65 bytes
 thats what it said

**Comment by generalwrex** [comment]
Closing all old open issues, please reopen or create a new one if these problems still exist!
