### ISSUE TITLE
SB4 Menu not working

### ISSUE THREAD

**Issue by ppodee17** [SnakeSVx/spacebuild#75]
Hey I install SB4 in gamemode then i start game in singleplayer and i got 2 lua errors
Couldn't include file 'shared\sb4_model_list.lua' (File not found) (@gamemodes/spacebuild/gamemode/shared.lua (line 75))
-
and
[ERROR] gamemodes/spacebuild/gamemode/client/spacebuild.lua:117: attempt to index local 'environment' (a nil value)
  1. Call - gamemodes/spacebuild/gamemode/client/spacebuild.lua:117
   2. func - gamemodes/spacebuild/gamemode/client/spacebuild.lua:48
    3. unknown - lua/includes/modules/net.lua:30

How can I fix it?
Sorry for my terrible english :D

**Comment by SnakeSVx** [comment]
I think this can be closed, since if SB4 is continued it will be made differently anyways.
